### ISSUE TITLE
German localisation should be improved

### ISSUE THREAD

**Issue by Luflosi** [python-humanize/humanize#48]
### What did you do?
Execute
```python
import humanize
import datetime as dt
_t = humanize.i18n.activate("de_DE")
humanize.naturaltime(dt.datetime.now() - dt.timedelta(seconds=3600))
```

### What did you expect to happen?
I would expect the output to be 'vor einer Stunde'.

### What actually happened?
The output was 'vor eine Stunde', which is grammatically incorrect.
"one hour" translates to "eine Stunde" but "one hour ago" translates to "vor einer Stunde". I think 1 is the only number where this special case happens.

### What versions are you using?

* OS: macOS 10.15.7
* Python: 3.10.5
* Humanize: 4.2.3

Overall the support for German seems a bit lacking.
For example the `.` and `,` in numbers are swapped compared to what's common in English, which this library doesn't support (`humanize.intcomma(12345)` for example).
`humanize.intword(123455913)` outputs `123.5 Million` but `Million` is singular. The correct output with a plural would be `123.5 Millionen`, since 123.5 is more than 1 (actually I think it's correct to always use the plural when the value is not exactly equal to 1).

Is this something you think would be worthwhile to improve? I could help you by trying to find more of these problems, testing patches or even writing some fixes myself if you help me a bit. I'm afraid if I just mess around in the translation file, I'll fix some specific problem I found but break other cases I didn't think about.

**Comment by carterbox** [comment]
The translation files are located here: https://github.com/python-humanize/humanize/tree/main/src/humanize/locale

I'm not sure whether they can handle a special case for single number like that because the pattern matches for "%s ago". Maybe poke around the language files and see if there are other languages that have a solution for this.

> humanize.intword(123455913) outputs 123.5 Million but Million is singular. The correct output with a plural would be 123.5 Millionen, since 123.5 is more than 1 (actually I think it's correct to always use the plural when the value is not exactly equal to 1).

The translation files do support this type of plural selection. It probably just needs to be implemented in the translation file for German ([see Spanish for an example](https://github.com/python-humanize/humanize/blob/14fc392cf49936fee06edd41863b1372ffc29d95/src/humanize/locale/ca_ES/LC_MESSAGES/humanize.po#L158)).

> For example the . and , in numbers are swapped compared to what's common in English, which this library doesn't support (humanize.intcomma(12345) for example).

Separator swapping is supported. [This is done for French.](https://github.com/python-humanize/humanize/blob/7688f204a994e55f8e607675363178e5d8424523/src/humanize/i18n.py#L17)

> I'm afraid if I just mess around in the translation file, I'll fix some specific problem I found but break other cases I didn't think about.

That's what unit tests are for 😉.

**Comment by Luflosi** [comment]
> Separator swapping is supported. [This is done for French.](https://github.com/python-humanize/humanize/blob/7688f204a994e55f8e607675363178e5d8424523/src/humanize/i18n.py#L17)

Are you sure this is supported? As far as I can tell, this only allows replacing `,` as the thousands separator with another character. Is there a way to also replace the decimal point `.` with another character? I think I will need to implement this myself.

**Comment by carterbox** [comment]
> Are you sure this is supported?

No. I suggest starting with a PR for the simplest translation fixes, then we can discuss in further detail the scope of replacing `.` with `,`.

**Comment by hugovk** [comment]
@Luflosi Anything left to fix here?

**Comment by Luflosi** [comment]
As you said in https://github.com/python-humanize/humanize/issues/93#issuecomment-1416746235, `intword` doesn't yet use `thousands_separator` and `decimal_separator`.
I also created https://github.com/python-humanize/humanize/issues/175 for another problem.
Since there are now GitHub issues for these problems, I'm fine with closing this issue.

Thank you for maintaining this project!
