### ISSUE TITLE
pip installation?

### ISSUE THREAD

**Issue by aress31** [python-humanize/humanize#55]
It seems that this lib is not yet available on the `pip`  registry. If you could installation steps to the doc, that would be great!

**Comment by hugovk** [comment]
This project has been on PyPI since October 2011:

https://pypi.org/project/humanize/

There are a couple of badges on the [README](https://github.com/python-humanize/humanize#readme), and it can be installed in the usual way, but I've updated the README and [docs](https://python-humanize.readthedocs.io/en/latest/) to include installation instructions:

## Installation

### From PyPI

```bash
python3 -m pip install --upgrade humanize
```

### From source

```bash
git clone https://github.com/github.com/python-humanize/humanize
cd humanize
python3 -m pip install -e .
```
